server:
  port: 9090

spring:
  application:
    name: daisy-courses
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/msvc_courses?useSSL=false&serverTimeZone=UTC&allPublicKeyRetrival=true
    username: postgres
    password: root2904
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG